services:

  app:
    #image: 4ch1m/pixoo-rest:latest
    build: .
    ports:
      - ${PIXOO_REST_PORT:-8000}:8000
    environment:
      - TZ=${TZ:-Europe/Berlin}
      #
      - PIXOO_HOST=${PIXOO_HOST:?}
      - PIXOO_SCREEN_SIZE=${PIXOO_SCREEN_SIZE:-64}
      - PIXOO_DEBUG=${PIXOO_DEBUG:-false}
      - PIXOO_CONNECTION_CHECK=${PIXOO_CONNECTION_CHECK:-true}
      - PIXOO_CONNECTION_CHECK_RETRIES=${PIXOO_CONNECTION_CHECK_RETRIES:-3}
      #
      - PIXOO_REST_DEBUG=${PIXOO_REST_DEBUG:-false}
    restart: unless-stopped
