label: pixoo-rest

restartPolicy: Always

replicaCount: 1

image:
  repository: 4ch1m/pixoo-rest
  pullPolicy: IfNotPresent
  tag: 2.0.0

livenessProbe:
  delay: 5
  period: 5

service:
  type: NodePort
  port: 8000

ingress:
  path: /pixoo-rest
  pathType: Prefix

environment:
  timezone: Europe/Berlin
  #
  pixoo_host: Pixoo64
  pixoo_screen_size: 64
  pixoo_debug: false
  pixoo_connection_check: true
  pixoo_connection_check_retries: 10
  pixoo_rest_debug: false
